name: 'OWASP Dependency-Check (SCA)'
description: 'Executa análise de dependências com OWASP Dependency-Check'
author: 'Security Team'

inputs:
  nvd-api-key:
    description: 'NVD API Key para Dependency-Check'
    required: true
  project-name:
    description: 'Nome do projeto'
    required: false
    default: ${{ github.event.repository.name }}
  scan-path:
    description: 'Caminho para scan'
    required: false
    default: '.'
  fail-on-error:
    description: 'Falhar o pipeline em caso de vulnerabilidades críticas'
    required: false
    default: 'false'
  output-formats:
    description: 'Formatos de saída (HTML, JSON, XML)'
    required: false
    default: 'HTML,JSON,XML'

outputs:
  report-path:
    description: 'Caminho do diretório com os relatórios'
    value: ${{ steps.scan.outputs.report-path }}

runs:
  using: 'composite'
  steps:
  - name: Criar diretórios necessários
    shell: bash
    run: |
      mkdir -p .odc-reports
      mkdir -p $HOME/OWASP-Dependency-Check/data
      mkdir -p $HOME/OWASP-Dependency-Check/data/cache
      echo "📁 Diretórios criados com sucesso"

  - name: 🔍 Debug Completo do Dependency-Check
    shell: bash
    run: |
      echo "=== ETAPA 1: Verificar API Key ==="
      if [ -z "${{ secrets.NVD_API_KEY }}" ]; then
          echo "❌ API Key está vazia!"
        exit 1
      fi
      echo "✅ API Key configurada (${#NVD_KEY} chars)"

      echo ""
      echo "=== ETAPA 2: Testar Conectividade ==="
      curl -v "https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=1" 2>&1 | head -20

      echo ""
      echo "=== ETAPA 3: Testar Container ==="
      docker run --rm owasp/dependency-check:latest --version

      echo ""
      echo "=== ETAPA 4: Scan Completo com Debug ==="
      docker run --rm \
        --volume $(pwd):/src \
        --volume $(pwd)/.odc-reports:/report \
        owasp/dependency-check:latest \
        --nvdApiKey "${{ secrets.NVD_API_KEY }}" \
        --scan /src/requirements.txt \
        -f HTML -f JSON \
        --project "debug-test" \
        --out /report \
        --enableExperimental \
        -v 2>&1

      echo ""
      echo "=== RESULTADO ==="
      ls -lah .odc-reports/

      if [ -f ".odc-reports/dependency-check-report.json" ]; then
          echo "✅ Relatório gerado com sucesso!"
          jq . .odc-reports/dependency-check-report.json | head -50
        else
          echo "❌ Relatório NÃO foi gerado!"
      fi
  env:
    NVD_KEY: ${{ secrets.NVD_API_KEY }}
